[unix_http_server]
file=/var/run/supervisor.sock

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisord]
nodaemon=true

[program:booster-motion]
directory=/app/booster_motion
command=/app/booster_motion/booster-motion -mode sim -config ./configs/config_isaac.lua
autostart=true
autorestart=true
priority=1
stdout_logfile=/var/log/booster-motion.log
stderr_logfile=/var/log/booster-motion.err

[program:delayed-starter]
command=/app/delayed_start.sh
autostart=true
autorestart=false
priority=2
startsecs=0
stdout_logfile=/var/log/delayed-starter.log
stderr_logfile=/var/log/delayed-starter.err

[program:simbridge]
directory=/app/bridge
command=/app/bridge/bin/simbridge_node
autostart=false
autorestart=true
stdout_logfile=/var/log/simbridge.log
stderr_logfile=/var/log/simbridge.err

[program:maximus]
directory=/app/maximus
command=/app/maximus/bin/maximus_main
environment=LD_LIBRARY_PATH="/app/maximus/tools/vision/tensorrt/TensorRT/targets/x86_64-linux-gnu/lib:/app/booster_motion/lib:/app/booster_motion/lib-usr-local:/app/booster_motion/lib-x86_64-linux-gnu",FASTRTPS_DEFAULT_PROFILES_FILE="/app/booster_motion/fastdds_profile.xml",SPQR_CONFIG_ROOT="/app/maximus/config",SPQR_BEHAVIOR_TREE_PATH="/app/maximus/behaviors"
autostart=false
autorestart=true
stdout_logfile=/var/log/maximus.log
stderr_logfile=/var/log/maximus.err

[program:colosseum]
directory=/app/colosseum
command=/app/colosseum/bin/main
environment=LD_LIBRARY_PATH="/app/booster_motion/lib:/app/booster_motion/lib-usr-local:/app/booster_motion/lib-x86_64-linux-gnu",FASTRTPS_DEFAULT_PROFILES_FILE="/app/booster_motion/fastdds_profile.xml"
autostart=false
autorestart=true
stdout_logfile=/var/log/colosseum.log
stderr_logfile=/var/log/colosseum.err
